### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by SchdowNVIDIA** [Alemiz112/StarGate-Universe#1]
It would be nice if the client tries reconnecting forever until it has got a connection.
At the moment i need to restart all servers when i took down the proxy for like 2 minutes.

Best regards,
Schdow

**Comment by Alemiz112** [comment]
Okay. This feature will come with next update.

**Comment by Alemiz112** [comment]
Done in 1006293a56374b012377dd4fdc7c0ad7bfa7c168
